name: covid-vaccine-notifier

on:
  workflow_dispatch:
  schedule:
    - cron: "*/1 * * * *" #runs for every 8hrs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: install pip packages
        run: |
          pip3 install -r requirements.txt
      - name: execute py script of age limit 18 # run the run.py to get the latest data
        run: |
          echo ${PINCODE}
          python3 run.py -t ${TOKEN} -c ${CHAT_ID_18} -p ${PINCODE} -s 4 -a 18
        env:
          TOKEN: ${{ secrets.TOKEN }}
          CHAT_ID_18: ${{ secrets.CHAT_ID_18 }}
          CHAT_ID_45: ${{ secrets.CHAT_ID_45 }}
          PINCODE: ${{ secrets.PINCODE }}
      - name: execute py script of age limit 45 # run the run.py to get the latest data
        run: |
          python3 run.py -t ${TOKEN} -c ${CHAT_ID_45} -p ${PINCODE} -s 4 -a 45
        env:
          TOKEN: ${{ secrets.TOKEN }}
          CHAT_ID_18: ${{ secrets.CHAT_ID_18 }}
          CHAT_ID_45: ${{ secrets.CHAT_ID_45 }}
          PINCODE: ${{ secrets.PINCODE }}
